import { motion, AnimatePresence } from 'framer-motion'
import { X } from 'lucide-react'
import { useEffect, useState } from 'react'
const sev={Critical:'text-red-400 border-red-500/30 bg-red-500/10',High:'text-amber-400 border-amber-500/30 bg-amber-500/10',Medium:'text-cyan-300 border-cyan-500/30 bg-cyan-500/10',Low:'text-slate-400 border-line bg-white/5',Valid:'text-emerald-400 border-emerald-500/30 bg-emerald-500/10',Pending:'text-amber-400 border-amber-500/30 bg-amber-500/10'}
export const Badge=({children})=><span className={`px-2 py-0.5 rounded border text-[11px] font-medium ${sev[children]||sev.Low}`}>{children}</span>
export function Counter({to}){const[v,setV]=useState(0);useEffect(()=>{let s=0;const id=setInterval(()=>{s+=Math.ceil(to/30);if(s>=to){s=to;clearInterval(id)}setV(s)},20);return()=>clearInterval(id)},[to]);return v.toLocaleString()}
export const MetricCard=({label,value,d})=>(<motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} whileHover={{y:-2}} className="card p-4"><div className="label">{label}</div><div className="text-2xl font-semibold mt-2"><Counter to={value}/></div><div className="text-xs text-accent mt-1">{d}</div></motion.div>)
export const ChartCard=({title,children,h=240,className=''})=>(<div className={`card p-4 ${className}`}><div className="label mb-3">{title}</div><div style={{height:h}}>{children}</div></div>)
export const PageHead=({title,sub,children})=>(<div className="flex flex-wrap items-end justify-between gap-3 mb-6"><div><div className="label">{sub}</div><h1 className="text-2xl font-semibold mt-1">{title}</h1></div><div className="flex gap-2 flex-wrap">{children}</div></div>)
export function DataTable({cols,rows,onRow}){return(<div className="card overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left border-b border-line">{cols.map(c=><th key={c.k} className="label px-4 py-3">{c.h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} onClick={()=>onRow&&onRow(r)} className="border-b border-line/60 hover:bg-white/5 cursor-pointer">{cols.map(c=><td key={c.k} className="px-4 py-3 whitespace-nowrap">{c.r?c.r(r):r[c.k]}</td>)}</tr>)}</tbody></table></div>)}
export function Drawer({open,onClose,title,children}){return(<AnimatePresence>{open&&<><motion.div className="fixed inset-0 bg-black/60 z-40" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={onClose}/><motion.aside className="fixed right-0 top-0 h-full w-full max-w-md bg-panel border-l border-line z-50 p-6 overflow-y-auto" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{type:'tween',duration:.25}}><div className="flex justify-between items-center mb-5"><h3 className="font-semibold">{title}</h3><button onClick={onClose}><X size={18}/></button></div>{children}</motion.aside></>}</AnimatePresence>)}
export const Filters=({items})=>(<div className="flex flex-wrap gap-2 mb-5">{items.map(([n,o])=><select key={n} className="input !w-auto" aria-label={n}>{o.map(x=><option key={x}>{x}</option>)}</select>)}</div>)
export const Bar=({v})=><div className="h-1.5 bg-line rounded"><div className="h-full rounded bg-accent" style={{width:v+'%'}}/></div>
